version: "3"

services:
  # code-server
  cdr:
    container_name: ide-cdr
    build:
      context: .
      dockerfile: ./cdr/Dockerfile
    environment:
      TZ: $TZ
      PASSWORD: $CDR_PASSWORD
      WILDFLY_ADMIN_NAME: $WILDFLY_ADMIN_NAME
      WILDFLY_ADMIN_PASSWORD: $WILDFLY_ADMIN_PASSWORD
    volumes:
        # DOOD
      - /var/run/docker.sock:/var/run/docker.sock
        # Local data (extensions, settings etc)
      - ./cdr/data:/home/coder/.local/share/code-server
        # Project
      - ./$APP_NAME:/home/coder/$APP_NAME
        # Maven repository
      - $HOME/.m2/repository:/home/coder/.m2/repository
        # WAS deploy and logs
      - ./wildfly/deployments:/home/coder/wildfly/standalone/deployments
      - ./wildfly/logs:/home/coder/wildfly/standalone/log
    ports:
      - 127.0.0.1:8081:8080
    networks:
      intranet: 
        ipv4_address: 172.18.0.11

  # database
  psql:
    container_name: ide-psql
    build:
      context: .
      dockerfile: ./psql/Dockerfile
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_SCHEMA: $POSTGRES_SCHEMA
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
        # Database Data
      - psql-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      intranet:
        ipv4_address: 172.18.0.12
  
  # query tool
  pgadmin4:
    container_name: ide-pga
    image: dpage/pgadmin4:6.11
    environment:
      TZ: $TZ
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    volumes:
      - ./pga/data:/var/lib/pgadmin
    ports:
      - 127.0.0.1:5433:80
    networks:
      intranet:
        ipv4_address: 172.18.0.13

  # WAS
  wildfly:
    container_name: ide-was
    build:
      context: .
      dockerfile: ./wildfly/Dockerfile
      args:
        WILDFLY_ADMIN_NAME: $WILDFLY_ADMIN_NAME
        WILDFLY_ADMIN_PASSWORD: $WILDFLY_ADMIN_PASSWORD
    environment:
      TZ: $TZ
    volumes:
        # WAS deploy and logs
      - ./wildfly/deployments:/opt/jboss/wildfly/standalone/deployments
      - ./wildfly/logs:/opt/jboss/wildfly/standalone/log
    ports:
        # Application
      - 127.0.0.1:8082:8080
        # Management Console
      - 127.0.0.1:8083:9990
    networks:
      intranet:
        ipv4_address: 172.18.0.14

networks:
  intranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  psql-data:
