version: "3"

services:
  # database
  psql:
    environment:
      POSTGRES_PASSWORD: "ghdfhr"
    image: postgres:9-alpine
    volumes:
        # database data
      - psql-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      intranet:
        ipv4_address: 172.18.0.12
  
  # query tool
  pgadmin4:
    environment:
      PGADMIN_DEFAULT_EMAIL: "hongrr123@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "ghdfhr"
    image: dpage/pgadmin4:4.29
    volumes:
      - ./pga-data:/var/lib/pgadmin
    ports:
      - 127.0.0.1:5433:80
    networks:
      intranet:
        ipv4_address: 172.18.0.13

  # WAS
  wildfly:
    environment:
      TZ: "Asia/Seoul"
    build:
      context: .
      dockerfile: ./bean-cafe-Dockerfile
    volumes:
        # maven repository
      - $HOME/.m2/repository:/root/.m2/repository
        # tomcat deploy (wired with cdr)
      - ./bean-cafe/deployments:/opt/jboss/wildfly/standalone/deployments
        # wildfly logs (wired with cdr)
      - ./bean-cafe/logs:/opt/jboss/wildfly/standalone/log
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:9990:9990
    networks:
      intranet:
        ipv4_address: 172.18.0.14

networks:
  intranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  psql-data:
