version: "3"

services:
  # code-server
  cdr:
    environment:
      TZ: "Asia/Seoul"
    build:
      context: .
      dockerfile: ./cdr-Dockerfile
    volumes:
        # dood
      - /var/run/docker.sock:/var/run/docker.sock
        # data (extensions, settings etc)
      - ./cdr-data:/home/coder/.local/share/code-server
        # project
      - ./bean-cafe:/home/coder/bean-cafe
        # maven repository
      - $HOME/.m2/repository:/home/coder/.m2/repository
        # wildfly deploy (wired with wildfly)
      - deployments:/home/coder/wildfly/standalone/deployments
        # wildfly logs (wired with cdr)
      - logs:/home/coder/wildfly/standalone/log
    ports:
      - 127.0.0.1:8081:8080
    networks:
      intranet: 
        ipv4_address: 172.18.0.11

  # database
  psql:
    environment:
      POSTGRES_PASSWORD: "ghdfhr"
    image: postgres:9-alpine
    volumes:
        # database data
      - psql-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      intranet:
        ipv4_address: 172.18.0.12
  
  # query tool
  pgadmin4:
    environment:
      PGADMIN_DEFAULT_EMAIL: "hongrr123@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "ghdfhr"
    image: dpage/pgadmin4:latest
    volumes:
      - pga-data:/var/lib/pgadmin
    ports:
      - 127.0.0.1:5433:80
    networks:
      intranet:
        ipv4_address: 172.18.0.13

  # WAS
  wildfly:
    environment:
      TZ: "Asia/Seoul"
    build:
      context: .
      dockerfile: ./bean-cafe-Dockerfile
    volumes:
        # maven repository
      - $HOME/.m2/repository:/root/.m2/repository
        # tomcat deploy (wired with cdr)
      - deployments:/opt/jboss/wildfly/standalone/deployments
        # wildfly logs (wired with cdr)
      - logs:/opt/jboss/wildfly/standalone/log
    ports:
      - 127.0.0.1:8082:8080
    networks:
      intranet:
        ipv4_address: 172.18.0.14

networks:
  intranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  deployments:
  logs:
  psql-data:
  pga-data:
